# =========================
# MongoDB Configuration
# =========================
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/lms_loan_application_db

  # =========================
  # Kafka Producer Configuration
  # =========================
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

# =========================
# Custom Kafka Topics
# =========================
kafka:
  topics:
    loan-application: loan.application.events

# =========================
# Actuator (recommended)
# =========================
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh

# =========================
# Logging
# =========================
logging:
  level:
    com.lms.loanapplication: DEBUG
